AppBundle\Entity\User:
    properties:
    # Your custom fields in your user entity, here is an example with FirstName
        name:
            - NotBlank:
                message: fos_user.name.blank
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.name.short
                max: 255
                maxMessage: fos_user.name.long
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
        last_name:
            - NotBlank:
                message: fos_user.last_name.blank
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.last_name.short
                max: 255
                maxMessage: fos_user.last_name.long
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
        address:
            - NotBlank:
                message: fos_user.address.blank
                groups: [ "AppBundleProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.address.short
                max: 255
                maxMessage: fos_user.address.long
                groups: [ "AppBundleProfile" ]


AppBundle\Entity\Billing:
    properties:
    # Your custom fields in your user entity, here is an example with FirstName
        number:
            - NotBlank:
                message: billing.number.blank
                groups: [ "AppBundleBilling"]
            - Length:
                min: 2
                minMessage: billing.number.short
                max: 100
                maxMessage: billing.number.long
                groups: [ "AppBundleBilling"]
        # date:
        #     - NotBlank:
        #         message: fos_user.date.blank
        #         groups: [ "AppBundleRegistration", "AppBundleProfile" ]
        #     - Length:
        #         min: 2
        #         minMessage: fos_user.date.short
        #         max: 255
        #         maxMessage: fos_user.date.long
        #         groups: [ "AppBundleBilling"]
        description:
            - NotBlank:
                message: billing.description.blank
                groups: [ "AppBundleProfile" ]
            - Length:
                min: 2
                minMessage: billing.description.short
                max: 255
                maxMessage: billing.description.long
                groups: [ "AppBundleBilling"]
        total:
            - NotBlank:
                message: billing.total.blank
                groups: [ "AppBundleBilling"]
            - Length:
                min: 1
                minMessage: billing.total.short
                max: 100
                maxMessage: billing.total.long
                groups: [ "AppBundleBilling"]



# Note: We still want to validate the email
# See FOSUserBundle/Resources/config/validation/orm.xml to understand
# the UniqueEntity constraint that was originally applied to both
# username and email fields
#
# As you can see, we are only applying the UniqueEntity constraint to 
# the email field and not the username field.
FOS\UserBundle\Model\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: 
             fields: email
             errorPath: email 
             message: fos_user.email.already_used
             groups: [ "AppBundleRegistration", "AppBundleProfile" ]

    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "AppBundleRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "AppBundleRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "AppBundleRegistration", "AppBundleProfile", "ResetPassword", "ChangePassword"]

FOS\UserBundle\Model\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "AppBundleRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "AppBundleRegistration" ]

FOS\UserBundle\Propel\User:
    properties:
        email:
            - NotBlank:
                message: fos_user.email.blank
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]
            - Length:
                min: 2
                minMessage: fos_user.email.short
                max: 255
                maxMessage: fos_user.email.long
                groups: [ "AppBundleRegistration", "ResetPassword" ]
            - Email:
                message: fos_user.email.invalid
                groups: [ "AppBundleRegistration", "AppBundleProfile" ]

        plainPassword:
            - NotBlank:
                message: fos_user.password.blank
                groups: [ "AppBundleRegistration", "ResetPassword", "ChangePassword" ]
            - Length:
                min: 2
                max: 4096
                minMessage: fos_user.password.short
                groups: [ "AppBundleRegistration", "AppBundleProfile", "ResetPassword", "ChangePassword"]


FOS\UserBundle\Propel\Group:
    properties:
        name:
            - NotBlank:
                message: fos_user.group.blank
                groups: [ "AppBundleRegistration" ]
            - Length:
                min: 2
                minMessage: fos_user.group.short
                max: 255
                maxMessage: fos_user.group.long
                groups: [ "AppBundleRegistration" ]